/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hcomlab.anggaranbelanja;

import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author hidayat
 */
public class MainFrame extends javax.swing.JFrame {
    
    int sheetTo=0;
    Connection db;

    /**
     * Creates new form NewJFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabInduk = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuTambah = new javax.swing.JMenuItem();
        menuSembunyikan = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuKeluar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuSimpan = new javax.swing.JMenuItem();
        menuHapus = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabInduk.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jMenu1.setText("File");

        menuTambah.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuTambah.setText("Tambah");
        menuTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTambah(evt);
            }
        });
        jMenu1.add(menuTambah);

        menuSembunyikan.setText("Sembunyikan");
        menuSembunyikan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSembunyikanActionPerformed(evt);
            }
        });
        jMenu1.add(menuSembunyikan);
        jMenu1.add(jSeparator1);

        menuKeluar.setText("Keluar");
        jMenu1.add(menuKeluar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        menuSimpan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuSimpan.setText("Simpan");
        menuSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSimpanActionPerformed(evt);
            }
        });
        jMenu2.add(menuSimpan);

        menuHapus.setText("Hapus");
        menuHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHapusActionPerformed(evt);
            }
        });
        jMenu2.add(menuHapus);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabInduk, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabInduk, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuTambah(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTambah
        Dok tab = new Dok();
        tab.setConnection(db);
        sheetTo++;
        tabInduk.addTab("Sheet "+Integer.toString(sheetTo), tab);
    }//GEN-LAST:event_menuTambah

    private void menuSembunyikanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSembunyikanActionPerformed
        tabInduk.removeTabAt(tabInduk.getSelectedIndex());
    }//GEN-LAST:event_menuSembunyikanActionPerformed

    private Dok form(){
        return (Dok)tabInduk.getComponentAt(tabInduk.getSelectedIndex());
    }
    
    private void menuSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSimpanActionPerformed
        form().simpan();
    }//GEN-LAST:event_menuSimpanActionPerformed

    private void menuHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHapusActionPerformed
        int hapus=JOptionPane.showConfirmDialog(this, "Hapus data ini?", "Hapus", JOptionPane.YES_NO_OPTION);
        if(JOptionPane.YES_OPTION==hapus){
            form().hapus();
        }
    }//GEN-LAST:event_menuHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem menuHapus;
    private javax.swing.JMenuItem menuKeluar;
    private javax.swing.JMenuItem menuSembunyikan;
    private javax.swing.JMenuItem menuSimpan;
    private javax.swing.JMenuItem menuTambah;
    private javax.swing.JTabbedPane tabInduk;
    // End of variables declaration//GEN-END:variables
}
